sudo: required
language: node_js
cache:
  yarn: true
node_js:
  - "12"
  - "10"
services:
  - docker
addons:
  chrome: stable
  firefox: latest
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn --ignore-engines
<<<<<<< HEAD
  - yarn build
=======
  - yarn run lerna run build --ignore selenium-ide-extension --ignore selenium-ide-extension-boilerplate
  - NODE_ENV="staging" yarn build:ext
  - docker-compose up -d
>>>>>>> 848d0409eeadf99c71d12a0e0c1e34d89d47d65e
script:
  - yarn typecheck
  - yarn lint
  - yarn test
