version: '3'
services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8080:80"
    volumes:
      - "./tests/static:/usr/share/nginx/html:ro"
  selenium:
    image: "selenium/standalone-chrome:4.0.0-beta-3-20210426"
    ports:
      - "4444:4444"
    volumes:
      - "./packages/selenium-ide/build:/ext-build"
