on:
  push:
    branches: [trunk]

jobs:
  release:
    name: Release IDE to GitHub for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: mac

    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    if: github.repository == 'seleniumhq/selenium-ide'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Install dependencies
        run: pnpm -r i
      - name: Install dependencies
        run: npm run install-app-deps
        working-directory: ./packages/selenium-ide
      - name: Build all JS
        run: pnpm run build
        env:
          NODE_ENV: "production"
      - name: Build selenium-ide binaries
        run: npm run build:electron:${{ matrix.platform }}
        working-directory: ./packages/selenium-ide
      - name: Set env from current release
        run: >
          echo "SIDE_RELEASE_VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV
        if: matrix.platform != 'windows-latest'
        working-directory: ./packages/selenium-ide
      - name: Set env from current release on Windows
        run: |
          $version = node -pe "require('./package.json').version"
          echo "SIDE_RELEASE_VERSION=$version" | Out-File -Append -Encoding utf8 $Env:GITHUB_ENV
        shell: pwsh
        if: matrix.platform == 'windows-latest'
        working-directory: ./packages/selenium-ide
      - name: Check env is there
        run: echo "${{ env.SIDE_RELEASE_VERSION }}"
      - name: Release latest selenium-ide on github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-${{ matrix.platform }}"
          prerelease: true
          title: "Nightly (Unstable)"
          files: packages/selenium-ide/dist/Selenium*
      - name: Release selenium-ide on github
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.SIDE_RELEASE_VERSION }}-${{ matrix.platform }}"
          prerelease: false
          files: packages/selenium-ide/dist/Selenium*
        continue-on-error: true