name: 'Release'

on:
  push:
    branches: frunk

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: yarn
      - name: Build app
        run: yarn build