name: 'Release'

on:
  push:
    branches: frunk

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
      - run: yarn
      - name: Build app
      - run: yarn build