name: 'Release'

on:
  push:
    branches: frunk

jobs:
  release:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish non IDE packages to npm
        run: npx lerna publish -y from-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build selenium-ide JS
        run: yarn build
      - name: Install electron-builder dependencies
        run: yarn workspace @seleniumhq/selenium-ide add dmg-license
      - name: Build selenium-ide binaries
        run: yarn build:electron