name: 'Test Selenium IDE'

on:
  pull_request:
    branches:
      - trunk
jobs:
  test:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      issues: read
      discussions: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: read
      statuses: read
    runs-on: ubuntu-latest
    if: github.repository == 'seleniumhq/selenium-ide'
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.11.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm -r i
      - name: Build side-runner and selenium-ide
        run: npm run build
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb x11-xserver-utils
      - name: Run all tests and also use xvfb
        run: xvfb-run --server-num=99 npm run test:ci
        env:
          DISPLAY: :99
